### ISSUE TITLE
Create an ansible vault for local development

### ISSUE THREAD

**Issue by computate** [computate-org-mce1/computate-org-mce1#16]
### Create an ansible vault for your local development.

Help each member of the team interested in local development to create and edit an encrypted ansible vault with a password for the host secrets for your development inventory.

```bash
install -d /usr/local/src/computate-org-mce1/inventories/$USER-localhost/host_vars/localhost/
ansible-vault create /usr/local/src/computate-org-mce1/inventories/$USER-localhost/host_vars/localhost/vault
ansible-vault edit /usr/local/src/computate-org-mce1/inventories/$USER-localhost/host_vars/localhost/vault
```

The contents of the vault will contain the secrets needed to override any default values you want to change in the app defaults defined here.

https://github.com/computate/computate/blob/master/ansible/roles/computate_scolaire/defaults/main.yml

There are descriptions for each of the fields.
There are several sections of fields, including:

- app system defaults
- Ansible defaults
- Zookeeper defaults
- Solr defaults
- PostgreSQL defaults
- computate-medical global defaults
- app US English defaults
- SMTP defaults
- OpenID Connect auth server defaults
- SSL/TLS defaults

Here is an example of the contents of the ansible vault for local development: 

```yaml

####################
# Certbot defaults #
####################

COMPUTATE_CERTBOT_DOMAIN_NAME: "..."

######################################
# computate-scolaire system defaults #
######################################

# The name of this application. 
COMPUTATE_SCOLAIRE_NAME: computate-scolaire
# The default source code directory for the computate application which helps generate and translate most the code. 
COMPUTATE_SRC: "/usr/local/src/computate"
# The default source code directory for the computate-scolaire project. 
COMPUTATE_SCOLAIRE_SRC: "/usr/local/src/{{COMPUTATE_SCOLAIRE_NAME}}"
# The default language of the computate-scolaire project code which is French in France. 
COMPUTATE_SCOLAIRE_LANG: "frFR"
# The default config file for the computate-scolaire project. 
COMPUTATE_SCOLAIRE_CONFIG: "{{COMPUTATE_SCOLAIRE_SRC}}/config/{{COMPUTATE_SCOLAIRE_NAME}}.config"
# The US English config file for the computate-scolaire project. 
COMPUTATE_SCOLAIRE_CONFIG_enUS: "{{COMPUTATE_SCOLAIRE_SRC}}/config/{{COMPUTATE_SCOLAIRE_NAME}}-enUS.config"
# The systemd service name for computate-scolaire that generates and translates most of the code. 
COMPUTATE_SCOLAIRE_SERVICE: "watch-{{COMPUTATE_SCOLAIRE_NAME}}"
# The systemd service file for computate-scolaire that generates and translates most of the code. 
COMPUTATE_SCOLAIRE_SYSTEMD: "/usr/lib/systemd/system/{{COMPUTATE_SCOLAIRE_SERVICE}}.service"
# The main git repository for the computate-scolaire project. 
COMPUTATE_SCOLAIRE_REPO: "git@github.com:computate-org/{{ COMPUTATE_SCOLAIRE_NAME }}.git"
# The target ansible inventory group for the computate-scolaire project to setup your own hosts under this name to deploy the application to. 
target: computate_scolaire

######################
# Zookeeper defaults #
######################

# The default hostname for the Zookeeper cluster manager. 
ZOOKEEPER_HOST_NAME: "localhost"
# The default port that Zookeeper runs to manage the cluster. 
ZOOKEEPER_PORT: 2181

#################
# Solr defaults #
#################

# The installation directory of Solr. 
SOLR_OPT: /opt/solr
# The default hostname for the Solr search engine. 
SOLR_HOST_NAME: localhost
# The default port that Solr runs. 
SOLR_PORT: 8983

#######################
# PostgreSQL defaults #
#######################

# The default hostname for the PostreSQL database. 
POSTGRES_HOST_NAME: "localhost"
# The default username that the PostgreSQL server runs with. 
POSTGRES_BECOME_USER: "postgres"
# The default path to the PostgreSQL hba file to manage user permissions. 
POSTGRES_HBA_CONF: "/var/lib/pgsql/data/pg_hba.conf"
# The default PostgreSQL service name. 
POSTGRES_SERVICE: "postgresql"

######################################
# computate-scolaire global defaults #
######################################

# The base URL where the static files will point to.  
COMPUTATE_SCOLAIRE_STATIC_BASE_URL: "https://computate.neocities.org/scolaire"
# The number of background worker executors that may run. 
COMPUTATE_SCOLAIRE_NUMBER_EXECUTORS: 5
# The properties file where the SSL/TLS encryption is configured. 
COMPUTATE_SCOLAIRE_SSL_PROPERTIES_FILENAME: computate-scolaire-keystore.properties

#############################################
# computate-scolaire France French defaults #
#############################################

# The domain name of the site. 
COMPUTATE_SCOLAIRE_DOMAIN_NAME_FRFR: "{{ COMPUTATE_CERTBOT_DOMAIN_NAME }}"
# The host name of the site. 
COMPUTATE_SCOLAIRE_SITE_HOST_NAME_FRFR: "scolaire-dev.{{ COMPUTATE_SCOLAIRE_DOMAIN_NAME_FRFR }}"
# The port of the site. 
COMPUTATE_SCOLAIRE_SITE_PORT_FRFR: "10480"
# The base URL of the site. 
COMPUTATE_SCOLAIRE_SITE_BASE_URL_FRFR: "https://{{ COMPUTATE_SCOLAIRE_SITE_HOST_NAME_FRFR }}:{{ COMPUTATE_SCOLAIRE_SITE_PORT_FRFR }}"
# The Solr collection of the site. 
COMPUTATE_SCOLAIRE_SOLR_COLLECTION_FRFR: "ecole"
# The timezone of the site. 
COMPUTATE_SCOLAIRE_SITE_ZONE_FRFR: "America/Denver"
# The PostgreSQL database host name of the site. 
COMPUTATE_SCOLAIRE_DB_HOST_NAME_FRFR: "localhost"
# The PostgreSQL database user name of the site. 
COMPUTATE_SCOLAIRE_DB_USER_FRFR: "..."
# The PostgreSQL database password of the site. 
COMPUTATE_SCOLAIRE_DB_PASSWORD_FRFR: "..."
# The PostgreSQL database name of the site. 
COMPUTATE_SCOLAIRE_DB_NAME_FRFR: ecole
# The Java main class of the site. 
COMPUTATE_SCOLAIRE_JAVA_MAIN_CLASS_FRFR: org.computate.scolaire.frFR.vertx.AppliVertx
# The backup directory of the site. 
COMPUTATE_SCOLAIRE_BACKUP_DIR_FRFR: /usr/local/src/computate-scolaire-static/data/frFR
# The restore directory of the site. 
COMPUTATE_SCOLAIRE_RESTORE_DIR_FRFR: /usr/local/src/computate-scolaire-static/data/frFR/Monday

##########################################
# computate-scolaire US English defaults #
##########################################

# The domain name of the site. 
COMPUTATE_SCOLAIRE_DOMAIN_NAME_ENUS: "{{ COMPUTATE_CERTBOT_DOMAIN_NAME }}"
# The host name of the site. 
COMPUTATE_SCOLAIRE_SITE_HOST_NAME_ENUS: "scolaire-dev.{{ COMPUTATE_SCOLAIRE_DOMAIN_NAME_ENUS }}"
# The port of the site. 
COMPUTATE_SCOLAIRE_SITE_PORT_ENUS: "10481"
# The base URL of the site. 
COMPUTATE_SCOLAIRE_SITE_BASE_URL_ENUS: "https://{{ COMPUTATE_SCOLAIRE_SITE_HOST_NAME_ENUS }}:{{ COMPUTATE_SCOLAIRE_SITE_PORT_ENUS }}"
# The Solr collection of the site. 
COMPUTATE_SCOLAIRE_SOLR_COLLECTION_ENUS: "school"
# The timezone of the site. 
COMPUTATE_SCOLAIRE_SITE_ZONE_ENUS: "America/Denver"
# The PostgreSQL database host name of the site. 
COMPUTATE_SCOLAIRE_DB_HOST_NAME_ENUS: "localhost"
# The PostgreSQL database user name of the site. 
COMPUTATE_SCOLAIRE_DB_USER_ENUS: "..."
# The PostgreSQL database password of the site. 
COMPUTATE_SCOLAIRE_DB_PASSWORD_ENUS: "..."
# The PostgreSQL database name of the site. 
COMPUTATE_SCOLAIRE_DB_NAME_ENUS: school
# The Java main class of the site. 
COMPUTATE_SCOLAIRE_JAVA_MAIN_CLASS_ENUS: org.computate.scolaire.enUS.vertx.AppVertx
# The backup directory of the site. 
COMPUTATE_SCOLAIRE_BACKUP_DIR_ENUS: /usr/local/src/computate-scolaire-static/data/enUS
# The restore directory of the site. 
COMPUTATE_SCOLAIRE_RESTORE_DIR_ENUS: /usr/local/src/computate-scolaire-static/data/enUS/Monday

#################
# SMTP defaults #
#################

# The email SMTP host name. 
EMAIL_HOST_NAME: smtp.example.com
# The email SMTP port. 
EMAIL_PORT: 465
# The email SMTP from email address. 
EMAIL_FROM: "..."
# Whether email SMTP SSL/TLS encryption is enabled. 
EMAIL_SSL: true
# Whether email SMTP username password authentication is enabled. 
EMAIL_AUTH: true
# The email SMTP username. 
EMAIL_USER: "..."
EMAIL_PASSWORD: "..."

#######################################
# OpenID Connect auth server defaults #
#######################################

# The Auth realm. 
AUTH_REALM: EXAMPLE.COM
# The Auth client or resource. 
AUTH_RESOURCE: example.com
# The Auth secret. 
AUTH_SECRET: "..."
# The Auth URL. 
AUTH_URL: "https://sso.{{ COMPUTATE_CERTBOT_DOMAIN_NAME }}/auth"

####################
# SSL/TLS defaults #
####################

# The keystore alias. 
SSL_ALIAS: "{{COMPUTATE_SCOLAIRE_DOMAIN_NAME_ENUS}}"
# The keystore directory. 
SSL_KEYSTORE_PATH: /opt/keystore
# The keystore properties filename. 
SSL_PROPERTIES_FILENAME: "{{COMPUTATE_SCOLAIRE_SSL_PROPERTIES_FILENAME}}"
# The keystore filename. 
SSL_JKS_FILENAME: "{{SSL_ALIAS}}.jks"
# The keystore path. 
SSL_JKS_PATH: "{{SSL_KEYSTORE_PATH}}/{{SSL_JKS_FILENAME}}"
# The certificate filename. 
SSL_CRT_FILENAME: "{{SSL_ALIAS}}.crt"
# The certificate path. 
SSL_CRT_PATH: "{{SSL_KEYSTORE_PATH}}/{{SSL_CRT_FILENAME}}"
# The private key filename. 
SSL_KEY_FILENAME: "{{SSL_ALIAS}}.key"
# The private key path. 
SSL_KEY_PATH: "{{SSL_KEYSTORE_PATH}}/{{SSL_KEY_FILENAME}}"
# The p12 file password. 
SSL_P12_PASSWORD: "..."
# The keystore file password. 
SSL_JKS_PASSWORD: "{{SSL_P12_PASSWORD}}"
# The keystore file base64 encoded (base64 -w 0 /opt/keystore/heytate.com.jks). 
SSL_JKS_BASE64: "..."
# The jceks file base64 encoded (base64 -w 0 /opt/keystore/heytate.com.jceks). 
SSL_JCEKS_BASE64: "..."

####################
# Ansible defaults #
####################

# Add to an ansible-vault the username of your user on your computer (echo $HOSTNAME). 
USER_NAME: "..."
# Add to an ansible-vault the password of your user on your computer to become root for configuring the applications. 
USER_PASSWORD: "..."
# Setup the ansible user when running the playbook as your user. 
ansible_user: "{{USER_NAME}}"
# Setup the ansible sudo password as your password when running the playbook. 
ansible_sudo_pass: "{{USER_PASSWORD}}"
# Setup the ansible password for elevated privileges as your password when running the playbook. 
ansible_become_pass: "{{USER_PASSWORD}}"
# Setup the ansible password for ssh as your password when running the playbook. 
ansible_ssh_pass: "{{USER_PASSWORD}}"
# Setup the decryption password for decrypting other secrets in the playbook. 
VAULT_PASSWORD: "{{USER_PASSWORD}}"

```

Look for values to override, especially those like this: "...".
